// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/setup-tasks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/setup-tasks.get').default>>>>
    }
    '/api/admin/users/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/list.get').default>>>>
    }
    '/api/admin/users/permissions': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/permissions.post').default>>>>
    }
    '/api/admin/users/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/update.post').default>>>>
    }
    '/api/auth/forgot-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/forgot-password.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/auth/reset-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/reset-password.post').default>>>>
    }
    '/api/clean/processos': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/clean/processos.delete').default>>>>
    }
    '/api/compras': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/compras/index').default>>>>
    }
    '/api/dashboard/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/stats.get').default>>>>
    }
    '/api/estoque/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/estoque/[id].delete').default>>>>
    }
    '/api/estoque': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/estoque/index').default>>>>
    }
    '/api/fornecedores': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fornecedores').default>>>>
    }
    '/api/itens': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/itens.get').default>>>>
    }
    '/api/ops/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id].put').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/index.get').default>>>>
    }
    '/api/ops/:id/:processoId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/[processoId].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/[processoId].put').default>>>>
    }
    '/api/ops/:id/actions': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/actions.post').default>>>>
    }
    '/api/ops/:id/pcp/generate-os': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/pcp/generate-os.post').default>>>>
    }
    '/api/ops/:id/pecas/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/pecas/import.post').default>>>>
    }
    '/api/ops/:id/pecas': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/pecas/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/pecas/index.post').default>>>>
    }
    '/api/ops/:id/processos/:processoId': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/processos/[processoId].put').default>>>>
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/processos/[processoId]/index.delete').default>>>>
    }
    '/api/ops/:id/processos/:processoId/concluir': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/processos/[processoId]/concluir.post').default>>>>
    }
    '/api/ops/:id/processos/:processoId/iniciar': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/processos/[processoId]/iniciar.post').default>>>>
    }
    '/api/ops/:id/processos/:processoId/pausar': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/processos/[processoId]/pausar.post').default>>>>
    }
    '/api/ops/:id/processos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/processos/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/processos/index.post').default>>>>
    }
    '/api/ops/:id/processos/template': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/processos/template.post').default>>>>
    }
    '/api/ops': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/index.post').default>>>>
    }
    '/api/ops/recent': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/recent.get').default>>>>
    }
    '/api/pcp/budget-email': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pcp/budget-email.post').default>>>>
    }
    '/api/pcp/ordens-servico/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pcp/ordens-servico/[id].get').default>>>>
    }
    '/api/pcp/ordens-servico': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pcp/ordens-servico/index.get').default>>>>
    }
    '/api/pecas/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pecas/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pecas/[id].patch').default>>>>
    }
    '/api/pecas/:id/desenho': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pecas/[id]/desenho.post').default>>>>
    }
    '/api/pecas/:id/processos': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pecas/[id]/processos').default>>>>
    }
    '/api/pecas/:id/reservar': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pecas/[id]/reservar.post').default>>>>
    }
    '/api/pecas/anexos/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pecas/anexos/[id].delete').default>>>>
    }
    '/api/salvar': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/salvar.post').default>>>>
    }
    '/api/user': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/index.get').default>>>>
    }
    '/api/user/modules': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/modules.get').default>>>>
    }
    '/api/user/tasks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/tasks.get').default>>>>
    }
    '/api/user/update-profile': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/update-profile.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}