// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/forgot-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/forgot-password.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/auth/reset-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/reset-password.post').default>>>>
    }
    '/api/clean/processos': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/clean/processos.delete').default>>>>
    }
    '/api/dashboard/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/stats.get').default>>>>
    }
    '/api/itens': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/itens.get').default>>>>
    }
    '/api/ops/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id].put').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/index.get').default>>>>
    }
    '/api/ops/:id/:processoId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/[processoId].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/[processoId].put').default>>>>
    }
    '/api/ops/:id/actions': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/actions.post').default>>>>
    }
    '/api/ops/:id/processos/:processoId': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/processos/[processoId].put').default>>>>
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/processos/[processoId]/index.delete').default>>>>
    }
    '/api/ops/:id/processos/:processoId/concluir': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/processos/[processoId]/concluir.post').default>>>>
    }
    '/api/ops/:id/processos/:processoId/iniciar': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/processos/[processoId]/iniciar.post').default>>>>
    }
    '/api/ops/:id/processos/:processoId/pausar': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/processos/[processoId]/pausar.post').default>>>>
    }
    '/api/ops/:id/processos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/processos/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/processos/index.post').default>>>>
    }
    '/api/ops/:id/processos/template': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/[id]/processos/template.post').default>>>>
    }
    '/api/ops': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/index.post').default>>>>
    }
    '/api/ops/recent': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ops/recent.get').default>>>>
    }
    '/api/salvar': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/salvar.post').default>>>>
    }
    '/api/user': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/index.get').default>>>>
    }
    '/api/user/modules': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/modules.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}